services:
  - type: web
    name: echovoyages-backend
    env: docker
    image: sameera04/echovoyages-backend:latest
    envVars:
      - key: MONGO_URI
        sync: false # Prevents exposing the value in the dashboard
      - key: JWT_SECRET
        value: Voyage_secret
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          name: echovoyages-frontend
          type: web
          property: url

services:
  # Backend API service
  - type: web
    name: echovoyages-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true

  # Frontend service
  - type: web
    name: echovoyages-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://echovoyages-backend.onrender.com
    autoDeploy: true
