services:
  # Backend API service
  - type: web
    name: echovoyages-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: npm run start
    dockerContext: ./
    buildTarget: backend
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://saiananyakatakam:NLnqR9ifdN8qbVft@cluster0.lbvmb.mongodb.net/EchoVoyages2
      - key: JWT_SECRET
        value: Voyage_secret
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://echovoyages-frontend.onrender.com
    healthCheckPath: /
    autoDeploy: true

  # Frontend service
  - type: web
    name: echovoyages-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    buildTarget: frontend
    envVars:
      - key: VITE_API_URL
        value: https://echovoyages-backend.onrender.com
    autoDeploy: true

