services:
  # Backend API service
  - type: web
    name: echovoyages-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: npm run start
    dockerContext: ./
    buildTarget: backend
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true

  # Frontend service
  - type: web
    name: echovoyages-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    buildTarget: frontend
    envVars:
      - key: VITE_API_URL
        value: https://echovoyages-backend.onrender.com
    autoDeploy: true

