services:
  - type: web
    name: echovoyages-backend
    env: docker
    image: sameera04/echovoyages-backend:latest
    envVars:
      - key: MONGO_URI
        sync: false # Prevents exposing the value in the dashboard
      - key: JWT_SECRET
        value: Voyage_secret
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          name: echovoyages-frontend
          type: web
          property: url
