services:
  # Backend API service
  - type: web
    name: echovoyages-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

  # Frontend service
  - type: web
    name: echovoyages-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://echovoyages-backend.onrender.com
    autoDeploy: true

